
again: all

all:
	pdflatex troy_1

clean:
	rm -f troy_1.aux
	rm -f troy_1.log
	rm -f troy_1.nav
	rm -f troy_1.out
	rm -f troy_1.snm
	rm -f troy_1.toc
	rm -f troy_1.vrb

distclean:
	rm -f troy_1.pdf

