
package pilot
{
  //////////////////////////////////////////////////////////////////////////////
  //
  //
  //
  enum state
  {
    Unknown   =  0,
    New       =  1,
    Pending   =  2,
    Running   =  3,
    Done      =  4,
    Canceled  =  5,
    Failed    =  6
  };

} // package pilot

